[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../backend/"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

# Production context
[context.production]
  environment = { 
    URL = "https://tryself.ai",
    VITE_API_URL = "https://self-ai-production.up.railway.app/api",
    VITE_ENABLE_ANALYTICS = "true",
    VITE_ENABLE_MOCK_DATA = "false"
  }

# Deploy Preview context
[context.deploy-preview]
  environment = { 
    VITE_ENABLE_ANALYTICS = "false",
    VITE_ENABLE_MOCK_DATA = "true"
  }

# Branch Deploy context
[context.branch-deploy]
  environment = { 
    VITE_ENABLE_ANALYTICS = "false",
    VITE_ENABLE_MOCK_DATA = "true"
  }

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self'; 
      connect-src 'self' https://self-ai-production.up.railway.app https://*.infura.io; 
      img-src 'self' https: data:; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval'; 
      style-src 'self' 'unsafe-inline';
      font-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      """

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"