[build]
builder = "NIXPACKS"
nixpacksConfigPath = "backend/nixpacks.toml"

[deploy]
startCommand = "cd backend && npm ci --only=production --no-audit --no-fund && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"